google/libsxg

.travis.yml
.travis/install_cmake.sh
.travis/install_openssl.sh
README.md

add travis.ci

---

CMakeLists.txt
Dockerfile

I forgot to apend this very important function.

Add library install section

---

CMakeLists.txt
docs/gensxg.md
src/gensxg.c

`gensxg` is small executable which generates SXG file as a command line tool.
It is useful for demonstrating what libsxg can do.
I'll write .deb script in another PR.

Append command line tool for generating SXG file

---

docs/sxg_signer_list.md

fix typo: s/Emty/Empty/

---

tests/test_util.h

Follow the google C++ code style https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes

test_util.h order of includes

---

fuzzers/signer_fuzzer.cc

There is unnecessary blank line.

remove extra blank line

---

README.md

The name is changed via https://github.com/google/libsxg/pull/22

follow the change of document filename

---

tests/test_util.cc

remove unrequired spaces

---

src/gensxg.c

closes #23 
flags are aligned.

align with gen-signedexchange

---

src/gensxg.c

as discussed in https://github.com/google/libsxg/pull/32#discussion_r353055995

gensxg: close opened file after use

---

CMakeLists.txt

From conversation https://github.com/google/libsxg/pull/21#pullrequestreview-333793942

use CMAKE_INSTALL variables to allow modify install target

---

CMakeLists.txt

Use CMAKE default feature instead of flag trick.

use CMAKE_CXX_FLAGS_DEBUG

---

src/gensxg.c
src/sxg_header.c

Some warnings happened in release build.
Resolve them.

eliminate warnings

---

.clang-format

Use google default format like [this](https://github.com/google/googletest/blob/master/.clang-format).

use clang-format

---

CMakeLists.txt
include/libsxg/sxg_cert_chain.h
src/gencertchain.c
src/gensxg.c
src/sxg_cert_chain.c
tests/sxg_cert_chain_test.cc

I did
```$ git ls-tree --full-tree -r HEAD | grep -e "\.\(c\|h\|hpp\|cpp\|cc\)\$" | cut -f 2 | xargs clang-format -style=file -i```

apply clang-format

---

CMakeLists.txt

From conversation https://github.com/google/libsxg/pull/21#pullrequestreview-333793942

refactoring test dependency structures

---

README.md
docs/gencertchain.md
docs/gensxg.md
docs/index.md
docs/internals.md
docs/sxg_buffer.md
docs/sxg_encoded_response.md
docs/sxg_header.md
docs/sxg_raw_response.md
docs/sxg_signer_list.md

Partially found via markdownlint.

Fix grammar and Markdown nits

---

.markdownlint
CMakeLists.txt

as mentioned #56, we should use [markdownlint](https://github.com/DavidAnson/markdownlint) and automate.
CI action file will be appended in another PR.

apply markdownlint and append custom target

---

CMakeLists.txt
docs/gencertchain.1
docs/gencertchain.md
docs/gensxg.1
docs/gensxg.md
docs/index.md
docs/libsxg.3
docs/libsxg.md

Hand-written `man` file is recommended to match debian culture.

add man file with roff format

---

README.md

These were required in the cmake call when I tried it.

Add CMAKE_INSTALL_{LIB,BIN}DIR to readme.

---

.travis.yml
.travis/install_boringssl.sh
.travis/install_go.sh
CMakeLists.txt
include/libsxg/sxg_signer_list.h
src/sxg_codec.c
src/sxg_sig.c

testing a travis build with boringssl. see: https://github.com/google/libsxg/issues/78

add boringssl build to travis

---

.github/workflows/release-action.yml

align release-action.yml with make-deb.yml

---

README.md

Instead of CMAKE_INSTALL_{LIB,BIN}DIR.

Document CMAKE_INSTALL_PREFIX.

---

CMakeLists.txt
src/sxg_cert_chain.c

OCSP: max retries and delay with backoff

---

CMakeLists.txt
src/verifysignature.c

Initial check-in of verifysignature code.

Add verifysignature code and integrate into build file.
