packaging/debian/control

OpenSSL 1.1.1c is current default version of Debian 10 (which is my normal environment).
But building and installing libsxg into other systems, 1.1.1c is too latest (e.g. Ubuntu 18.04LTS uses OpenSSL 1.1.1).
Downgrade dependency version will enable libsxg to install in more environments.

OpenSSL 1.1.1 is enough for build

---

.gitignore
packaging/build_all_debs
packaging/dockerfiles/deb.dockerfile

Automatically generate .deb files for 
- `debian-buster` (Debian 10)
- `debian-stretch` (Debian 9)
- `ubuntu-disco` (Ubuntu 19.04)
- `ubuntu-bionic` (Ubuntu 18.04 LTS)
Patterns.

Build .deb file for multiple linux distributions with Docker.

---

docs/gensxg.md
src/gensxg.c

output `integrity hash` from gensxg will be helpful to support generating SXG with subresource prefetching.
Usage will be looks like
```bash
$ ./gensxg -url https://example.com
-certUrl https://example.com/cert.cbor
-validityUrl https://example.com/validity.msg
-certificate ./prime256v1.pem
-privateKey ./prime256v1.key
-header "link: <https://example.com/logo.png>;rel=allowed-alt-sxg;header-integrity=\"`./gensxg -integrity -content ./logo.png -contentType image/png`\""
-header "link: <https://example.com/logo.png>;rel=preload;as=image"
-content ./myFile.html > myFile.html.sxg
```

add integrity mode

---

tests/sxg_codec_test.cc

Supresses the following warning:
type qualifiers ignored on cast result type [-Wignored-qualifiers]

Prefer casting to const data, not const pointer

---

README.md

Supresses the following warnings:
```
sxgsample.c:13:24: warning: implicit declaration of function ‘PEM_read_PrivateKey’; did you mean ‘i2d_PrivateKey’? [-Wimplicit-function-declaration]
sxgsample.c:18:16: warning: implicit declaration of function ‘PEM_read_X509’ [-Wimplicit-function-declaration]
```

Include PEM headers in example

---

docs/gensxg.md
docs/sxg_buffer.md
docs/sxg_generate.md
docs/sxg_signer_list.md

Correct typos in docs

---

CMakeLists.txt
tests/nfail_malloc_test.cc
tests/sxg_buffer_test.cc
tests/sxg_codec_test.cc
tests/sxg_encoded_response_test.cc
tests/sxg_generate_test.cc
tests/sxg_header_test.cc
tests/sxg_sig_test.cc
tests/sxg_signer_list_test.cc
tests/test_util.cc
tests/test_util.h
tests/toplevel_test.cc

Move common functions as utility library. 
- `BufferToString`
- `StringToBuffer`
- `LoadX509Cert`
- `LoadPrivateKey`
- `LoadPublicKey`
- `LoadEd25519Pubkey`

Add test common library

---

src/sxg_header.c

- `PRIu64` requires `<inttypes.h>`
- `snprintf` requires `<stdio.h>`

add missing include header

---

src/sxg_signer_list.c

- `OPENSSL_free` requires `#include <openssl/crypto.h>`
- `EVP_PKEY_free` requires `#include <openssl/evp.h>`
dependency should be more verbose.

add missing header

---

CMakeLists.txt

closes #20 
try compile with `-fsanitize=fuzzer` option, and if it does not supported, give up to build fuzzer binary with leaving message.
Blocking gcc by the name is not a good idea because gcc may support fuzzer in future, so trying compile actually is a good way in my opinion.

use try_compile to check fuzzer supporting

---

CMakeLists.txt

Specifying project language allows cmake to determine compiling environment.

specify project language

---

CMakeLists.txt

`.so` is more useful than `.a` for users of the binary.

Cmake shared lib

---

CMakeLists.txt
include/libsxg/internal/sxg_buffer.h
include/libsxg/internal/sxg_cbor.h
include/libsxg/internal/sxg_header.h
src/sxg_buffer.c
src/sxg_cbor.c
src/sxg_cert_chain.c
src/sxg_header.c
tests/sxg_buffer_test.cc
tests/sxg_cbor_test.cc
tests/sxg_header_test.cc

closes #35 
a basic refactoring.
It includes some name change in internal functions for consistency.

extract and merge the cbor manipulation functions

---

CMakeLists.txt

- Bump version on packaging (because of interface changing related to cert-chain).
- Specify SO file version which is required by debian convention.

bump version to 0.2

---

.clang-format
.github/workflows/formatter.yml
src/gencertchain.c
src/gensxg.c
src/sxg_cbor.c
tests/sxg_cert_chain_test.cc

Default behavior is changed between clang `8.0.0` to `9.0.0`.
So explicitly specifying `Regroup` will be the best way to make it works well on both clang8 and clang9.

use IncludeBlocks: Regroup

---

.github/workflows/clang-format-validation.yml
.github/workflows/formatter.yml

This PR removes the dependency on https://github.com/kumagi/clang-format-action by
- stopping using docker as GitHub Actions itself offers runs-on option
- install (only) clang-format thorough apt instead of downloading whole clang+llvm
and pack everything into single and tiny yaml.
Also it turned out that [the check now runs in 30s](https://github.com/tomokinat/libsxg/commit/223afe264aad8c14095416606218d4756843d855/checks?check_suite_id=386307411) (time varies a lot among runs through), 7x faster than [current one](https://github.com/google/libsxg/commit/ce03fa07df8f92a77ab5ad46e70b0ea520a74c91/checks?check_suite_id=386257499).

simplify and optimize clang-format action

---

CMakeLists.txt

Generally, `libsxg.so.0` should point `libsxg.so.0.2` by symbolic link, but current project make `libsxg.so.0.2` points `libsxg.so.0`.
This is *INVERTED*.
```ShellSession
$ ls -l /usr/lib/x86_64-linux-gnu/libsxg* 
-rw-r--r-- 1 root root 38752 Dec 19 16:30 /usr/lib/x86_64-linux-gnu/libsxg.so.0
lrwxrwxrwx 1 root root    11 Dec 19 16:30 /usr/lib/x86_64-linux-gnu/libsxg.so.0.2 -> libsxg.so.0
```

VERSION and SOVERSION was inverted

---

CMakeLists.txt

Add an option (-DSXG_BUILD_STATIC, default off) to build a static library (libsxg.a) with make target sxg_static. Also added an option for existing shared library build(-DSXG_BUILD_SHARED, default on) and gensxg/gencertchain exectutables (-DSXG_BUILD_EXECUTABLES, default on) so that they can be disabled easilty. Default behavior should not be changed.
https://github.com/google/libsxg/issues/65

Add CMake options for static build

---

src/sxg_codec.c

BIO_f_base64 is deprecated in BoringSSL, and EVP_EncodeBlock/EVP_DecodeBlock is suggested as an alternative.
Note that the return type of EVP_EncodeBlock is size_t in BoringSSL and int in OpenSSL

Use EVP_EncodeBlock instead of BIO methods for BoringSSL compatibility

---

src/sxg_codec.c

Check for positive value and then cast from maybe-int to (unsigned)
size_t. Hopefully there are no platforms where size_t is an unsigned
char.
Fixes #72.
/cc @cpapazian

Eliminate mixed-sign comparison.

---

include/libsxg/internal/sxg_cbor.h
src/sxg_cbor.c

Consistently use size_t across header and implementation file.
Signed-off-by: Raul Gutierrez Segales <rgs@pinterest.com>

Fix build for OS X

---

CMakeLists.txt
include/libsxg/internal/sxg_codec.h
src/sxg_codec.c
tests/sxg_sig_test.cc

The ECDSA signature is a DER-encoded pair of integers, which results in
variable length. Change the assertion to remove the signature rather than
filling with % chars, so that it's resilient to this.
In addition, add an assertion that the signature is correct, by hard-coding an
expected signed message and then making all the necessary OpenSSL calls.
This was tested with
```bash
$ (attempts=0; display_attempts () { echo Attempts: $attempts; }; trap display_attempts INT && make sxg_sig_test && while 
./sxg_sig_test; do attempts=$(($attempts+1)); done)
...
^CAttempts: 4652
```
Fixes #76.
/cc @cpapazian @rgs1 Can you verify this works against BoringSSL?

Fix sxg_sig_test to allow variable-size sig.

---

src/sxg_cert_chain.c

as [document](https://www.openssl.org/docs/man1.1.0/man3/OCSP_sendreq_nbio.html) says, `OCSP_sendreq_nbio` returns 3 values.
```
-1: retry.
0: error.
1: success
```
Then this logic should handle error returned value to propagate the context to the return value.

handle error of OCSP_sendreq_nbio

---

.travis.yml
CMakeLists.txt
src/sxg_cert_chain.c
tests/sxg_cert_chain_test.cc

Add help text, so "ON" is interpreted as the default value.
/cc @cpapazian FYI be sure to override in your config

Fix SXG_WITH_CERT_CHAIN cmake option.

---

tests/sxg_cert_chain_test.cc

It turns out it should have been failing all along because it never mocks out
the OCSP response. I updated it to expect failure, while still validating the
OCSP request, and added a TODO to mock the response.
Fixes #87.

"Fix" CertChainTest.SendRequest.

---

.github/workflows/make-debs.yml
.github/workflows/release-action.yml

Change mount pounts to /packaging/output to match what
packaging/{Dockerfile,build_deb} do. This should fix the zip files attached to
push actions and releases so that they are no longer empty.

Fix mount point for GitHub workflows.

---

CMakeLists.txt

It was already at 3.13 for RUN_TEST=on. Now it's so for RUN_TEST=off, too,
based on anecdotal evidence. It's possible the actual minimum is somewhere in
between.
Fixes #93. /cc @cpapazian

Increase cmake minimum version from 3.0 to 3.13.

---

.travis.yml
.travis/install_cmake_old.sh
CMakeLists.txt
README.md

Change cmake_minimum_required to 3.1 (earliest I could easily test) and update
the README to specify CMAKE_INSTALL_LIBDIR=lib and CMAKE_INSTALL_BINDIR=bin,
which it seems only became the default somewhere between CMake 3.11 and 3.15
inclusive.
/cc @cpapazian

Add support for older versions of CMake.

---

src/sxg_cert_chain.c

* Apple devices such as macOS don’t have support
for clock_nanosleep
* When compiling on Apple devices, use nanosleep
instead

Use nanosleep on apple devices

---

CMakeLists.txt

Googletest repository's main tag has changed name to `main`. I'm not sure when it had been changed. 
In default CMakefile has described this as `master`. So it failed to make with following logs. I fixed tag's name.
```
% make
Scanning dependencies of target gtest
[  1%] Creating directories for 'gtest'
[  3%] Performing download step (git clone) for 'gtest'
Cloning into 'gtest'...
fatal: invalid reference: master
CMake Error at /Users/yugo-horie/libsxg/build/gtest-prefix/tmp/gtest-gitclone.cmake:40 (message):
Failed to checkout tag: 'master'
make[2]: *** [gtest-prefix/src/gtest-stamp/gtest-download] Error 1
make[1]: *** [CMakeFiles/gtest.dir/all] Error 2
make: *** [all] Error 2
```

Fix gtest branch in CMakefile.
